/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#2c1e1a",
        outline: "#817471",
        "outline-variant": "#d2c3bf",
        surface: "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "error-container": "#ffdad6",
        primary: "#130805",
        "surface-container-high": "#eae7e7",
        "inverse-primary": "#dac1bb",
        "secondary-fixed": "#ece1d2",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed": "#e5e2dd",
        "on-tertiary-container": "#8a8884",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c9c6c2",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-container": "#696255",
        "surface-dim": "#dcd9d9",
        "secondary-fixed-dim": "#cfc5b6",
        "primary-fixed-dim": "#dac1bb",
        "surface-tint": "#6d5a55",
        "primary-fixed": "#f7ddd6",
        error: "#ba1a1a",
        "surface-bright": "#fcf9f8",
        "on-background": "#1c1b1b",
        "on-secondary-fixed-variant": "#4c463b",
        "on-primary": "#ffffff",
        "surface-container": "#f0eded",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#4f4542",
        background: "#fcf9f8",
        "on-tertiary": "#ffffff",
        "on-surface": "#1c1b1b",
        "on-primary-fixed": "#261814",
        tertiary: "#0a0a08",
        "on-secondary-fixed": "#201b12",
        "secondary-container": "#e9decf",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        secondary: "#655d51",
        "on-tertiary-fixed-variant": "#474743",
        "inverse-surface": "#313030",
        "on-primary-container": "#99847e",
        "tertiary-container": "#21211e",
        "on-primary-fixed-variant": "#54433e",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed": "#1c1c19",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
